stages:
  - package
  - deploy

variables:
  DEPLOYMENT_TOOLS_IMAGE: iristrace/deployment-tools:20440
  IMAGE_REPO: "hub.iristrace.com/iristrace/monitor"

package:image:
  stage: package
  image: docker:24-dind
  services:
    - docker:24-dind
  script:
    - docker login -u $HUB_USER -p $HUB_PASSWORD hub.iristrace.com
    - |
      docker build \
        -t $IMAGE_REPO:$CI_PIPELINE_ID \
        -t $IMAGE_REPO:latest \
        .
    - docker push $IMAGE_REPO:$CI_PIPELINE_ID
    - docker push $IMAGE_REPO:latest
  only:
    - main

.deployment_script: &deployment-script
  image: hub.iristrace.com/$DEPLOYMENT_TOOLS_IMAGE
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh ./deploy
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-keyscan gitlab.iristrace.com >> ~/.ssh/known_hosts
    - echo "$ANSIBLE_VAULT_PASSWORD" | tr -d '\r' > ~/.vault-password
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd ./deploy
    - ansible-playbook
        --vault-password-file=~/.vault-password
        --extra-vars="swarm=$SWARM env=$ENV ci_pipeline_id=$CI_PIPELINE_ID hub_user=$HUB_USER hub_password=$HUB_PASSWORD"
        monitor.yml
        --limit $SWARM

.deploy: &deploy
  stage: deploy
  <<: *deployment-script

monitor-to-prd:
  <<: *deploy
  variables:
    ENV: "prd"
    STACK: "sergio"
    SWARM: "swarm-g007"
  when: manual
  only:
    - main
